export const LOAD_RULE_SUCCESS = 'LOAD_RULE_SUCCESS';
export const LOAD_RULES_SUCCESS = 'LOAD_RULES_SUCCESS';
export const SAVE_RULE_SUCCESS = 'SAVE_RULE_SUCCESS';
export const START_SAVE_RULE = 'START_SAVE_RULE';
