export const LOAD_RULE_SUCCESS = 'LOAD_RULE_SUCCESS';
export const LOAD_RULE_START = 'LOAD_RULE_START';
export const UPDATE_RULE_SUCCESS = 'UPDATE_RULE_SUCCESS';
export const LOAD_RULES_SUCCESS = 'LOAD_RULES_SUCCESS';
export const LOAD_RULES_START = 'LOAD_RULES_START';

export const SAVE_RULE_SUCCESS = 'SAVE_RULE_SUCCESS';
